### ISSUE TITLE
Dimmer2 Light 0 switch type

### ISSUE THREAD

**Issue by svde** [enesbcs/shellyteacher4domo#10]
Testing on one of my dimmer2's, I noticed that a RGB switch device is created, while the device only supports on/off + brightness, in mqtt_templates.txt:

`
payload={"name": "%shelly_id% Light 0", "cmd_t": "~light/0/set", "stat_t": "~light/0/status","payload_on": "{\"turn\":\"on\"}","payload_off": "{\"turn\":\"off\"}", "value_template": "{{value_json.ison}}","stat_tpl": "{%if value_json.ison==true%}ON{%else%}OFF{%endif%}","brightness_command_topic":"\~light/0/set","brightness_state_topic":"~light/0/status","brightness": true,"color_mode": true,"supported_color_modes": ["onoff","brightness"], "brightness_scale":100, "bri_val_tpl":"{{value_json.brightness}}", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false", "uniq_id": "%shelly_id%-light-0", "qos": 0, "~": "shellies/%shelly_id%/"}
`

I guess shellyteacher4domo is doing this correctly, but Domoticz MQTT Autodiscovery is creating the RGB dimmer device, while a regular (single color) dimmer would be better.

**Comment by enesbcs** [comment]
What Domoticz version do you use? When i tested on the last beta version, a dimmer device created for Dimmer2 in Domoticz.

**Comment by svde** [comment]
Latest domoticz image from docker hub:
Version: 2023.1 (build 15182)
Build Hash: 34815c1a9
Compile Date: 2023-04-10 17:22:59
dzVents Version: 3.1.8
Python Version: 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]

This is the dimmer device it created:
![image](https://user-images.githubusercontent.com/572598/232535235-d9158cdb-9c0d-40ae-8022-cfb3f8d49a6a.png)

While this is the dimmer created by Shelly_MQTT:
![image](https://user-images.githubusercontent.com/572598/232535685-0284adf6-7144-451c-893e-f34bbc3ec392.png)

**Comment by enesbcs** [comment]
I see. The old plugin creates devices for itself, so it is irrevelant, as Domoticz MQTT AD hardware creates the devices in this case.
It may look otherwise on the GUI, but dimming is working, isn't it?

**Comment by svde** [comment]
Yes, it's working. But the old one (Shelly_MQTT) is more convenient, as you can turn on / off the light with one click. The new one requires to go through the color interface to access the on & off buttons, which (IMHO) adds no value.

**Comment by enesbcs** [comment]
Maybe if we change "supported_color_modes": ["onoff","brightness"] in the template to "supported_color_modes": ["brightness"] it may be better.
But i am afraid that every color device is an RGB device basically in Domoticz MQTT AD... maybe we can try "color_mode": false also, but i think it has no real effect as brightness defines a light device anyway.

**Comment by svde** [comment]
Yes, that fixed it.

But not quite. The percentage slider in the domoticz device stays at 0%, while the light is on (at for instance 50%). Not sure if it's related to what shellyteacher4domo does... Is anybody else seeing this?

**Comment by svde** [comment]
Opened: [PR#15](https://github.com/enesbcs/shellyteacher4domo/pull/15)
