### ISSUE TITLE
Add support for Shelly Gas

### ISSUE THREAD

**Issue by Bewo** [enesbcs/shellyteacher4domo#16]
https://shelly-api-docs.shelly.cloud/gen1/#shelly-gas-mqtt

I will try this... 

By the way:
@enesbcs and ALL other Contributors: THANKS for your great work!!

**Comment by enesbcs** [comment]
Thanks for volunteering!

As i see the GAS docs /sensor/concentration returns a simple number, it is similar than Door Window 2 lux for example, but "unit_of_meas" will be "ppm" which instructs Domo to make an AirQuality sensor.

Other values seems multi-select texts, see Door Window 2 Illumination for example.

**Comment by enesbcs** [comment]
> I will try this...

Do you need some help?

**Comment by enesbcs** [comment]
Basic support added at commit https://github.com/enesbcs/shellyteacher4domo/commit/a3e054ea05f294abd117721fd25039947c2952a3 needs checking!
