### ISSUE TITLE
Shelly Gen1 devices not showing "Online" status

### ISSUE THREAD

**Issue by Xavier82** [enesbcs/shellyteacher4domo#17]
In the first Shelly python Plugin the online status was reported (device_id e.g. "Shelly - shelly1-XXX-online".
In this new version (ShellyTeacher4Domo) this device_id isn't showing up anymore. Is there a reason?
How was this done in the Shelly Python Plugin? When I look at the MQTT Explorer for 1 of my Shelly1 devices I can't find "Online" state like with ShellyPlus2PM and ShellyPro4pm.

Is this somehting which can be fixed/made with ShellyTeacher4Domo?

**Comment by enesbcs** [comment]
Yep, there is a simple reason why i not created "online" devices in template files: i do not need them.

Although from 1.4.3 firmware shelly Gen1 devices has an /online MQTT topic with payload true/false. In theory at least.
https://shelly-api-docs.shelly.cloud/gen1/#availability-and-announces

You can try with these template:

```
topic=%discovery_prefix%/binary_sensor/%shelly_id%-online/config
payload={"name": "%shelly_id% Online", "stat_t": "~online", "uniq_id": "%shelly_id%-online", "~": "shellies/%shelly_id%/", "pl_on": "true", "pl_off": "false"}
```

**Comment by Xavier82** [comment]
Thanks!, code works, added to "mqtt_templates.txt".

Issue solved.
