### ISSUE TITLE
Incomplete MQTT GEN1 template Shelly Dimmer2

### ISSUE THREAD

**Issue by Xavier82** [enesbcs/shellyteacher4domo#18]
Trying to convert all my shelly devices to ShellyTeacher4Domo.
It seems the GEN1 Template of the Shelly Dimmer2 is incomplete.

Can u add this?

Path: shellies/shellydimmer2-XXX/light/0/status
payload:
`{
  "ison": false,
  "source": "input",
  "has_timer": false,
  "timer_started": 0,
  "timer_duration": 0,
  "timer_remaining": 0,
  "mode": "white",
  "brightness": 100,
  "transition": 0
}`

Path: shellies/shellydimmer2-XXX/light/0/power
`value`

Path: shellies/shellydimmer2-XXX/light/0/energy
`value`

Path: shellies/shellydimmer2-XXX/temperature
`value`

Path: shellies/shellydimmer2-XXX/temperature_f
`value`

Path: shellies/shellydimmer2-XXX/overtemperature
`value`

Path: shellies/shellydimmer2-XXX/overpower
`value`

Path: shellies/shellydimmer2-XXX/loaderror
`value`

Path: shellies/shellydimmer2-XXX/input/0
`value`

Path: shellies/shellydimmer2-XXX/input/1
`value`

Path: shellies/shellydimmer2-XXX/online
`value`

Path: shellies/shellydimmer2-XXX/announce
payload:
`{
  "id": "shellydimmer2-XXX",
  "model": "SHDM-2",
  "mac": "XXX",
  "ip": "192.168.0.114",
  "new_fw": false,
  "fw_ver": "20230510-082920/v1.13.1-gda6f9f2"
}`

Path: shellies/shellydimmer2-XXX/info
payload:
`{
  "wifi_sta": {
    "connected": true,
    "ssid": "Unifi beneden",
    "ip": "192.168.0.114",
    "rssi": -76
  },
  "cloud": {
    "enabled": false,
    "connected": false
  },
  "mqtt": {
    "connected": true
  },
  "time": "",
  "unixtime": 0,
  "serial": 1,
  "has_update": false,
  "mac": "XXX",
  "cfg_changed_cnt": 0,
  "actions_stats": {
    "skipped": 0
  },
  "lights": [
    {
      "ison": false,
      "source": "input",
      "has_timer": false,
      "timer_started": 0,
      "timer_duration": 0,
      "timer_remaining": 0,
      "mode": "white",
      "brightness": 100,
      "transition": 0
    }
  ],
  "meters": [
    {
      "power": 0,
      "overpower": 0,
      "is_valid": true,
      "timestamp": 0,
      "counters": [
        0,
        0,
        0
      ],
      "total": 0
    }
  ],
  "inputs": [
    {
      "input": 0,
      "event": "",
      "event_cnt": 0
    },
    {
      "input": 0,
      "event": "",
      "event_cnt": 0
    }
  ],
  "tmp": {
    "tC": 42.14,
    "tF": 107.85,
    "is_valid": true
  },
  "calibrated": true,
  "calib_progress": 0,
  "calib_status": 0,
  "calib_running": 0,
  "wire_mode": 1,
  "forced_neutral": false,
  "overtemperature": false,
  "loaderror": 0,
  "overpower": false,
  "debug": 0,
  "update": {
    "status": "unknown",
    "has_update": false,
    "new_version": "",
    "old_version": "20230510-082920/v1.13.1-gda6f9f2"
  },
  "ram_total": 49672,
  "ram_free": 37004,
  "fs_size": 233681,
  "fs_free": 116715,
  "uptime": 3
}`

Path: shellies/shellydimmer2-XXX/input_event/0
payload:
`{
  "event": "",
  "event_cnt": 0
}`

Path: shellies/shellydimmer2-XXX/input_event/1
payload:
`{
  "event": "",
  "event_cnt": 0
}`

Path: homeassistant/binary_sensor/shellydimmer2-XXX-overtemperature/config
payload:
`{
  "name": "shellydimmer2-XXX Overtemperature",
  "stat_t": "~overtemperature",
  "enabled_by_default": true,
  "uniq_id": "shellydimmer2-XXX-overtemperature",
  "qos": 0,
  "~": "shellies/shellydimmer2-XXX/",
  "entity_category": "diagnostic",
  "pl_on": "1",
  "pl_off": "0",
  "avty_t": "~online",
  "pl_avail": "true",
  "pl_not_avail": "false",
  "dev_cla": "problem"
}`

Path: homeassistant/binary_sensor/shellydimmer2-XXX-overload/config
payload:
`{
  "name": "shellydimmer2-XXX Overload",
  "stat_t": "~overload",
  "enabled_by_default": true,
  "uniq_id": "shellydimmer2-XXX-overload",
  "qos": 0,
  "~": "shellies/shellydimmer2-XXX/",
  "entity_category": "diagnostic",
  "pl_on": "1",
  "pl_off": "0",
  "avty_t": "~online",
  "pl_avail": "true",
  "pl_not_avail": "false",
  "dev_cla": "problem"
}`

Path: homeassistant/binary_sensor/shellydimmer2-XXX-loaderror/config
payload:
`{
  "name": "shellydimmer2-XXX Load error",
  "stat_t": "~loaderror",
  "enabled_by_default": true,
  "uniq_id": "shellydimmer2-XXX-loaderror",
  "qos": 0,
  "~": "shellies/shellydimmer2-XXX/",
  "entity_category": "diagnostic",
  "pl_on": "1",
  "pl_off": "0",
  "avty_t": "~online",
  "pl_avail": "true",
  "pl_not_avail": "false",
  "dev_cla": "problem"
}`

Path: homeassistant/binary_sensor/shellydimmer2-XXX-input-0/config
payload:
`{
  "name": "shellydimmer2-XXX Input 0",
  "stat_t": "~input/0",
  "enabled_by_default": true,
  "uniq_id": "shellydimmer2-XXX-input-0",
  "qos": 0,
  "~": "shellies/shellydimmer2-XXX/",
  "pl_on": "1",
  "pl_off": "0",
  "avty_t": "~online",
  "pl_avail": "true",
  "pl_not_avail": "false"
}`

Path: homeassistant/binary_sensor/shellydimmer2-XXX-input-1/config
payload:
`{
  "name": "shellydimmer2-XXX Input 1",
  "stat_t": "~input/1",
  "enabled_by_default": true,
  "uniq_id": "shellydimmer2-XXX-input-1",
  "qos": 0,
  "~": "shellies/shellydimmer2-XXX/",
  "pl_on": "1",
  "pl_off": "0",
  "avty_t": "~online",
  "pl_avail": "true",
  "pl_not_avail": "false"
}`

Path: homeassistant/binary_sensor/shellydimmer2-XXX-online/config
payload:
`{
  "name": "shellydimmer2-XXX Online",
  "stat_t": "~online",
  "uniq_id": "shellydimmer2-XXX-online",
  "~": "shellies/shellydimmer2-XXX/",
  "pl_on": "true",
  "pl_off": "false"
}`

Path: homeassistant/sensor/shellydimmer2-XXX/temperature/config
payload:
`{
  "name": "shellydimmer2-XXX Temperature",
  "stat_t": "~temperature",
  "frc_upd": "false",
  "enabled_by_default": true,
  "uniq_id": "shellydimmer2-XXX-temperature",
  "qos": 0,
  "~": "shellies/shellydimmer2-XXX/",
  "entity_category": "diagnostic",
  "dev_cla": "temperature",
  "stat_cla": "measurement",
  "unit_of_meas": "°C",
  "val_tpl": "{%if is_number(value) and -100<value|int<900%}{{value|round(1)}}{%else%}unknown{%endif%}",
  "avty_t": "~online",
  "pl_avail": "true",
  "pl_not_avail": "false",
  "device": {
    "identifiers": [
      "XXX"
    ],
    "manufacturer": "Shelly",
    "model": "SHDM-2",
    "name": "shellydimmer2-XXX"
  }
}`

Path: homeassistant/sensor/shellydimmer2-XXX-0/power/config
payload:
`{
  "name": "shellydimmer2-XXX Power 0",
  "stat_t": "~light/0/power",
  "avty_t": "~online",
  "pl_avail": "true",
  "pl_not_avail": "false",
  "frc_upd": "false",
  "enabled_by_default": true,
  "uniq_id": "shellydimmer2-XXX-light-power-0",
  "qos": 0,
  "~": "shellies/shellydimmer2-XXX/",
  "dev_cla": "power",
  "stat_cla": "measurement",
  "unit_of_meas": "W",
  "val_tpl": "{{value|float|round(1)}}",
  "device": {
    "identifiers": [
      "XXX"
    ],
    "manufacturer": "Shelly",
    "model": "SHDM-2",
    "name": "shellydimmer2-XXX"
  }
}`

Path: homeassistant/sensor/shellydimmer2-XXX-0/overpower/config
payload:
`{
  "name": "shellydimmer2-XXX Overpower 0",
  "stat_t": "~light/0/overpower_value",
  "avty_t": "~online",
  "pl_avail": "true",
  "pl_not_avail": "false",
  "frc_upd": "false",
  "enabled_by_default": true,
  "uniq_id": "shellydimmer2-XXX-light-overpowervalue-0",
  "qos": 0,
  "~": "shellies/shellydimmer2-XXX/",
  "dev_cla": "power",
  "stat_cla": "measurement",
  "unit_of_meas": "W",
  "val_tpl": "{{value|float|round(1)}}",
  "device": {
    "identifiers": [
      "XXX"
    ],
    "manufacturer": "Shelly",
    "model": "SHDM-2",
    "name": "shellydimmer2-XXX"
  }
}`

Path: homeassistant/sensor/shellydimmer2-XXX-0/energy/config
payload:
`{
  "name": "shellydimmer2-XXX Energy 0",
  "stat_t": "~light/0/energy",
  "avty_t": "~online",
  "pl_avail": "true",
  "pl_not_avail": "false",
  "frc_upd": "false",
  "enabled_by_default": false,
  "uniq_id": "shellydimmer2-XXX-light-energy-0",
  "qos": 0,
  "~": "shellies/shellydimmer2-XXX/",
  "dev_cla": "energy",
  "stat_cla": "total_increasing",
  "unit_of_meas": "Wh",
  "val_tpl": "{{(value|float/60)|round(2)}}",
  "device": {
    "identifiers": [
      "XXX"
    ],
    "manufacturer": "Shelly",
    "model": "SHDM-2",
    "name": "shellydimmer2-XXX"
  }
}`

Path: homeassistant/select/shellydimmer2-XXX/input_event-0/config
payload:
`{
  "name": "shellydimmer2-XXX Input Event 0",
  "json_attributes_topic": "~input_event/0",
  "value_template": "{{value_json.event}}",
  "cmd_t": "~dummy",
  "frc_upd": "false",
  "enabled_by_default": true,
  "uniq_id": "shellydimmer2-XXX-event-0",
  "~": "shellies/shellydimmer2-XXX/",
  "dev_cla": "event",
  "stat_cla": "selector",
  "ops": [
    "-",
    "S",
    "L"
  ]
}`

Path: homeassistant/select/shellydimmer2-XXX/input_event-1/config
payload:
`
{
  "name": "shellydimmer2-XXX Input Event 1",
  "json_attributes_topic": "~input_event/1",
  "value_template": "{{value_json.event}}",
  "cmd_t": "~dummy",
  "frc_upd": "false",
  "enabled_by_default": true,
  "uniq_id": "shellydimmer2-XXX-event-1",
  "~": "shellies/shellydimmer2-XXX/",
  "dev_cla": "event",
  "stat_cla": "selector",
  "ops": [
    "-",
    "S",
    "L"
  ]
}`

Path: homeassistant/select/shellydimmer2-XXX-0/config
payload:
`{
  "name": "shellydimmer2-XXX Light 0",
  "cmd_t": "~light/0/set",
  "stat_t": "~light/0/status",
  "payload_on": "{\"turn\":\"on\"}",
  "payload_off": "{\"turn\":\"off\"}",
  "value_template": "{{value_json.ison}}",
  "stat_tpl": "{%if value_json.ison==true%}ON{%else%}OFF{%endif%}",
  "brightness_command_topic": "~light/0/set",
  "brightness_state_topic": "~light/0/status",
  "brightness": true,
  "color_mode": true,
  "supported_color_modes": [
    "brightness"
  ],
  "brightness_scale": 100,
  "bri_val_tpl": "{{value_json.brightness}}",
  "avty_t": "~online",
  "pl_avail": "true",
  "pl_not_avail": "false",
  "uniq_id": "shellydimmer2-XXX-light-0",
  "qos": 0,
  "~": "shellies/shellydimmer2-XXX/"
}`

**Comment by enesbcs** [comment]
> Trying to convert all my shelly devices to ShellyTeacher4Domo. It seems the GEN1 Template of the Shelly Dimmer2 is incomplete.
> 
> Can u add this?

Can you be a little more specific? Which one?

These are already implemented:

```
[SHDM-1][SHDM-2][SHDM-1-white][SHDM-2-white] # Shelly Dimmer 1/2
topic=%discovery_prefix%/sensor/%shelly_id%/temperature/config
payload={"name": "%shelly_id% Temperature", "stat_t": "~temperature", "frc_upd": "false", "enabled_by_default": true, "uniq_id": "%shelly_id%-temperature", "qos": 0, "~": "shellies/%shelly_id%/", "entity_category": "diagnostic", "dev_cla": "temperature", "stat_cla": "measurement", "unit_of_meas": "°C", "val_tpl": "{%if is_number(value) and -100<value|int<900%}{{value|round(1)}}{%else%}unknown{%endif%}", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false","device": {"identifiers": ["%shelly_mac%"],"manufacturer": "Shelly","model": "%shelly_model%","name": "%shelly_id%"}}
topic=%discovery_prefix%/binary_sensor/%shelly_id%-overtemperature/config
payload={"name": "%shelly_id% Overtemperature", "stat_t": "~overtemperature", "enabled_by_default": true, "uniq_id": "%shelly_id%-overtemperature", "qos": 0,  "~": "shellies/%shelly_id%/", "entity_category": "diagnostic", "pl_on": "1", "pl_off": "0", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false", "dev_cla": "problem"}
topic=%discovery_prefix%/binary_sensor/%shelly_id%-overload/config
payload={"name": "%shelly_id% Overload", "stat_t": "~overload", "enabled_by_default": true, "uniq_id": "%shelly_id%-overload", "qos": 0,  "~": "shellies/%shelly_id%/", "entity_category": "diagnostic", "pl_on": "1", "pl_off": "0", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false", "dev_cla": "problem"}
topic=%discovery_prefix%/binary_sensor/%shelly_id%-loaderror/config
payload={"name": "%shelly_id% Load error", "stat_t": "~loaderror", "enabled_by_default": true, "uniq_id": "%shelly_id%-loaderror", "qos": 0,  "~": "shellies/%shelly_id%/", "entity_category": "diagnostic", "pl_on": "1", "pl_off": "0", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false", "dev_cla": "problem"}
topic=%discovery_prefix%/sensor/%shelly_id%-0/power/config
payload={"name": "%shelly_id% Power 0", "stat_t": "~light/0/power", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false", "frc_upd": "false", "enabled_by_default": true, "uniq_id": "%shelly_id%-light-power-0", "qos": 0, "~": "shellies/%shelly_id%/", "dev_cla": "power", "stat_cla": "measurement", "unit_of_meas": "W", "val_tpl": "{{value|float|round(1)}}","device": {"identifiers": ["%shelly_mac%"],"manufacturer": "Shelly","model": "%shelly_model%","name": "%shelly_id%"}}
topic=%discovery_prefix%/sensor/%shelly_id%-0/overpower/config
payload={"name": "%shelly_id% Overpower 0", "stat_t": "~light/0/overpower_value", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false", "frc_upd": "false", "enabled_by_default": true, "uniq_id": "%shelly_id%-light-overpowervalue-0", "qos": 0, "~": "shellies/%shelly_id%/", "dev_cla": "power", "stat_cla": "measurement", "unit_of_meas": "W", "val_tpl": "{{value|float|round(1)}}","device": {"identifiers": ["%shelly_mac%"],"manufacturer": "Shelly","model": "%shelly_model%","name": "%shelly_id%"}}
topic=%discovery_prefix%/sensor/%shelly_id%-0/energy/config
payload={"name": "%shelly_id% Energy 0", "stat_t": "~light/0/energy", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false", "frc_upd": "false", "enabled_by_default": false, "uniq_id": "%shelly_id%-light-energy-0", "qos": 0, "~": "shellies/%shelly_id%/", "dev_cla": "energy", "stat_cla": "total_increasing", "unit_of_meas": "Wh", "val_tpl": "{{(value|float/60)|round(2)}}","device": {"identifiers": ["%shelly_mac%"],"manufacturer": "Shelly","model": "%shelly_model%","name": "%shelly_id%"}}
topic=%discovery_prefix%/binary_sensor/%shelly_id%-input-0/config
payload={"name": "%shelly_id% Input 0", "stat_t": "~input/0", "enabled_by_default": true, "uniq_id": "%shelly_id%-input-0", "qos": 0,  "~": "shellies/%shelly_id%/", "pl_on": "1", "pl_off": "0", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false"}
topic=%discovery_prefix%/binary_sensor/%shelly_id%-input-1/config
payload={"name": "%shelly_id% Input 1", "stat_t": "~input/1", "enabled_by_default": true, "uniq_id": "%shelly_id%-input-1", "qos": 0,  "~": "shellies/%shelly_id%/", "pl_on": "1", "pl_off": "0", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false"}
topic=%discovery_prefix%/select/%shelly_id%/input_event-0/config
payload={"name": "%shelly_id% Input Event 0", "json_attributes_topic": "~input_event/0", "value_template":"{{value_json.event}}" , "cmd_t": "~dummy", "frc_upd": "false", "enabled_by_default": true, "uniq_id": "%shelly_id%-event-0", "~": "shellies/%shelly_id%/", "dev_cla": "event", "stat_cla": "selector" , "ops":["-","S","L"] }
topic=%discovery_prefix%/select/%shelly_id%/input_event-1/config
payload={"name": "%shelly_id% Input Event 1", "json_attributes_topic": "~input_event/1", "value_template":"{{value_json.event}}" , "cmd_t": "~dummy", "frc_upd": "false", "enabled_by_default": true, "uniq_id": "%shelly_id%-event-1", "~": "shellies/%shelly_id%/", "dev_cla": "event", "stat_cla": "selector" , "ops":["-","S","L"] }
topic=%discovery_prefix%/light/%shelly_id%-0/config
payload={"name": "%shelly_id% Light 0", "cmd_t": "~light/0/set", "stat_t": "~light/0/status","payload_on": "{\"turn\":\"on\"}","payload_off": "{\"turn\":\"off\"}", "value_template": "{{value_json.ison}}","stat_tpl": "{%if value_json.ison==true%}ON{%else%}OFF{%endif%}","brightness_command_topic":"~light/0/set","brightness_state_topic":"~light/0/status","brightness": true,"color_mode": true,"supported_color_modes": ["brightness"], "brightness_scale":100, "bri_val_tpl":"{{value_json.brightness}}", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false", "uniq_id": "%shelly_id%-light-0", "qos": 0, "~": "shellies/%shelly_id%/"}
```

**Comment by Xavier82** [comment]
Then these topics remain:
Path: shellies/shellydimmer2-XXX/light/0/status
payload:
`{
  "ison": false,
  "source": "input",
  "has_timer": false,
  "timer_started": 0,
  "timer_duration": 0,
  "timer_remaining": 0,
  "mode": "white",
  "brightness": 100,
  "transition": 0
}`

Path: shellies/shellydimmer2-XXX/light/0/power
`value`

Path: shellies/shellydimmer2-XXX/light/0/energy
`value`

Path: shellies/shellydimmer2-XXX/temperature
`value`

Path: shellies/shellydimmer2-XXX/temperature_f
`value`

Path: shellies/shellydimmer2-XXX/overtemperature
`value`

Path: shellies/shellydimmer2-XXX/overpower
`value`

Path: shellies/shellydimmer2-XXX/loaderror
`value`

Path: shellies/shellydimmer2-XXX/input/0
`value`

Path: shellies/shellydimmer2-XXX/input/1
`value`

Path: shellies/shellydimmer2-XXX/online
`value`

Path: shellies/shellydimmer2-XXX/announce
payload:
`{
  "id": "shellydimmer2-XXX",
  "model": "SHDM-2",
  "mac": "XXX",
  "ip": "192.168.0.114",
  "new_fw": false,
  "fw_ver": "20230510-082920/v1.13.1-gda6f9f2"
}`

Path: shellies/shellydimmer2-XXX/info
payload:
`{
  "wifi_sta": {
    "connected": true,
    "ssid": "Unifi beneden",
    "ip": "192.168.0.114",
    "rssi": -76
  },
  "cloud": {
    "enabled": false,
    "connected": false
  },
  "mqtt": {
    "connected": true
  },
  "time": "",
  "unixtime": 0,
  "serial": 1,
  "has_update": false,
  "mac": "XXX",
  "cfg_changed_cnt": 0,
  "actions_stats": {
    "skipped": 0
  },
  "lights": [
    {
      "ison": false,
      "source": "input",
      "has_timer": false,
      "timer_started": 0,
      "timer_duration": 0,
      "timer_remaining": 0,
      "mode": "white",
      "brightness": 100,
      "transition": 0
    }
  ],
  "meters": [
    {
      "power": 0,
      "overpower": 0,
      "is_valid": true,
      "timestamp": 0,
      "counters": [
        0,
        0,
        0
      ],
      "total": 0
    }
  ],
  "inputs": [
    {
      "input": 0,
      "event": "",
      "event_cnt": 0
    },
    {
      "input": 0,
      "event": "",
      "event_cnt": 0
    }
  ],
  "tmp": {
    "tC": 42.14,
    "tF": 107.85,
    "is_valid": true
  },
  "calibrated": true,
  "calib_progress": 0,
  "calib_status": 0,
  "calib_running": 0,
  "wire_mode": 1,
  "forced_neutral": false,
  "overtemperature": false,
  "loaderror": 0,
  "overpower": false,
  "debug": 0,
  "update": {
    "status": "unknown",
    "has_update": false,
    "new_version": "",
    "old_version": "20230510-082920/v1.13.1-gda6f9f2"
  },
  "ram_total": 49672,
  "ram_free": 37004,
  "fs_size": 233681,
  "fs_free": 116715,
  "uptime": 3
}`

Path: shellies/shellydimmer2-XXX/input_event/0
payload:
`{
  "event": "",
  "event_cnt": 0
}`

Path: shellies/shellydimmer2-XXX/input_event/1
payload:
`{
  "event": "",
  "event_cnt": 0
}`


Path: homeassistant/binary_sensor/shellydimmer2-XXX-online/config
payload:
`{
  "name": "shellydimmer2-XXX Online",
  "stat_t": "~online",
  "uniq_id": "shellydimmer2-XXX-online",
  "~": "shellies/shellydimmer2-XXX/",
  "pl_on": "true",
  "pl_off": "false"
}`

**Comment by enesbcs** [comment]
I am still a bit confused why you are repeating MQTT paths, which are already included in templates.

> Then these topics remain: Path: shellies/shellydimmer2-XXX/light/0/status payload: `{ "ison": false, "source": "input", "has_timer": false, "timer_started": 0, "timer_duration": 0, "timer_remaining": 0, "mode": "white", "brightness": 100, "transition": 0 }`

Already added:
```
topic=%discovery_prefix%/light/%shelly_id%-0/config
payload={"name": "%shelly_id% Light 0", "cmd_t": "~light/0/set", "stat_t": "~light/0/status","payload_on": "{\"turn\":\"on\"}","payload_off": "{\"turn\":\"off\"}", "value_template": "{{value_json.ison}}","stat_tpl": "{%if value_json.ison==true%}ON{%else%}OFF{%endif%}","brightness_command_topic":"~light/0/set","brightness_state_topic":"~light/0/status","brightness": true,"color_mode": true,"supported_color_modes": ["brightness"], "brightness_scale":100, "bri_val_tpl":"{{value_json.brightness}}", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false", "uniq_id": "%shelly_id%-light-0", "qos": 0, "~": "shellies/%shelly_id%/"}
```

> 
> Path: shellies/shellydimmer2-XXX/light/0/power `value`

Already added
```
topic=%discovery_prefix%/sensor/%shelly_id%-0/power/config
payload={"name": "%shelly_id% Power 0", "stat_t": "~light/0/power", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false", "frc_upd": "false", "enabled_by_default": true, "uniq_id": "%shelly_id%-light-power-0", "qos": 0, "~": "shellies/%shelly_id%/", "dev_cla": "power", "stat_cla": "measurement", "unit_of_meas": "W", "val_tpl": "{{value|float|round(1)}}","device": {"identifiers": ["%shelly_mac%"],"manufacturer": "Shelly","model": "%shelly_model%","name": "%shelly_id%"}}
```


> Path: shellies/shellydimmer2-XXX/light/0/energy `value`

Already added
```
topic=%discovery_prefix%/sensor/%shelly_id%-0/energy/config
payload={"name": "%shelly_id% Energy 0", "stat_t": "~light/0/energy", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false", "frc_upd": "false", "enabled_by_default": false, "uniq_id": "%shelly_id%-light-energy-0", "qos": 0, "~": "shellies/%shelly_id%/", "dev_cla": "energy", "stat_cla": "total_increasing", "unit_of_meas": "Wh", "val_tpl": "{{(value|float/60)|round(2)}}","device": {"identifiers": ["%shelly_mac%"],"manufacturer": "Shelly","model": "%shelly_model%","name": "%shelly_id%"}}
```


> Path: shellies/shellydimmer2-XXX/temperature `value`

Already added
```
topic=%discovery_prefix%/sensor/%shelly_id%/temperature/config
payload={"name": "%shelly_id% Temperature", "stat_t": "~temperature", "frc_upd": "false", "enabled_by_default": true, "uniq_id": "%shelly_id%-temperature", "qos": 0, "~": "shellies/%shelly_id%/", "entity_category": "diagnostic", "dev_cla": "temperature", "stat_cla": "measurement", "unit_of_meas": "°C", "val_tpl": "{%if is_number(value) and -100<value|int<900%}{{value|round(1)}}{%else%}unknown{%endif%}", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false","device": {"identifiers": ["%shelly_mac%"],"manufacturer": "Shelly","model": "%shelly_model%","name": "%shelly_id%"}}
```

> Path: shellies/shellydimmer2-XXX/temperature_f `value`

US citizens may add themself, modifying above temperature template

> Path: shellies/shellydimmer2-XXX/overtemperature `value`

Already added
```
topic=%discovery_prefix%/binary_sensor/%shelly_id%-overtemperature/config
payload={"name": "%shelly_id% Overtemperature", "stat_t": "~overtemperature", "enabled_by_default": true, "uniq_id": "%shelly_id%-overtemperature", "qos": 0,  "~": "shellies/%shelly_id%/", "entity_category": "diagnostic", "pl_on": "1", "pl_off": "0", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false", "dev_cla": "problem"}
```

> Path: shellies/shellydimmer2-XXX/overpower `value`

Already added
```
topic=%discovery_prefix%/sensor/%shelly_id%-0/overpower/config
payload={"name": "%shelly_id% Overpower 0", "stat_t": "~light/0/overpower_value", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false", "frc_upd": "false", "enabled_by_default": true, "uniq_id": "%shelly_id%-light-overpowervalue-0", "qos": 0, "~": "shellies/%shelly_id%/", "dev_cla": "power", "stat_cla": "measurement", "unit_of_meas": "W", "val_tpl": "{{value|float|round(1)}}","device": {"identifiers": ["%shelly_mac%"],"manufacturer": "Shelly","model": "%shelly_model%","name": "%shelly_id%"}}
```

> Path: shellies/shellydimmer2-XXX/loaderror `value`

Already added
```
topic=%discovery_prefix%/binary_sensor/%shelly_id%-loaderror/config
payload={"name": "%shelly_id% Load error", "stat_t": "~loaderror", "enabled_by_default": true, "uniq_id": "%shelly_id%-loaderror", "qos": 0,  "~": "shellies/%shelly_id%/", "entity_category": "diagnostic", "pl_on": "1", "pl_off": "0", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false", "dev_cla": "problem"}

```
 
> Path: shellies/shellydimmer2-XXX/input/0 `value`

Already added

```
topic=%discovery_prefix%/binary_sensor/%shelly_id%-input-0/config
payload={"name": "%shelly_id% Input 0", "stat_t": "~input/0", "enabled_by_default": true, "uniq_id": "%shelly_id%-input-0", "qos": 0,  "~": "shellies/%shelly_id%/", "pl_on": "1", "pl_off": "0", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false"}
```

> Path: shellies/shellydimmer2-XXX/input/1 `value`

Already added
```
topic=%discovery_prefix%/binary_sensor/%shelly_id%-input-1/config
payload={"name": "%shelly_id% Input 1", "stat_t": "~input/1", "enabled_by_default": true, "uniq_id": "%shelly_id%-input-1", "qos": 0,  "~": "shellies/%shelly_id%/", "pl_on": "1", "pl_off": "0", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false"}
```

> Path: shellies/shellydimmer2-XXX/online `value`

https://github.com/enesbcs/shellyteacher4domo/issues/17

> Path: shellies/shellydimmer2-XXX/announce payload: `{ "id": "shellydimmer2-XXX", "model": "SHDM-2", "mac": "XXX", "ip": "192.168.0.114", "new_fw": false, "fw_ver": "20230510-082920/v1.13.1-gda6f9f2" }`

Announce is used for detection, there are no sensor informations in it.

> Path: shellies/shellydimmer2-XXX/info payload: `{ "wifi_sta": { "connected": true, "ssid": "Unifi beneden", "ip": "192.168.0.114", "rssi": -76 }, "cloud": { "enabled": false, "connected": false }, "mqtt": { "connected": true }, "time": "", "unixtime": 0, "serial": 1, "has_update": false, "mac": "XXX", "cfg_changed_cnt": 0, "actions_stats": { "skipped": 0 }, "lights": [ { "ison": false, "source": "input", "has_timer": false, "timer_started": 0, "timer_duration": 0, "timer_remaining": 0, "mode": "white", "brightness": 100, "transition": 0 } ], "meters": [ { "power": 0, "overpower": 0, "is_valid": true, "timestamp": 0, "counters": [ 0, 0, 0 ], "total": 0 } ], "inputs": [ { "input": 0, "event": "", "event_cnt": 0 }, { "input": 0, "event": "", "event_cnt": 0 } ], "tmp": { "tC": 42.14, "tF": 107.85, "is_valid": true }, "calibrated": true, "calib_progress": 0, "calib_status": 0, "calib_running": 0, "wire_mode": 1, "forced_neutral": false, "overtemperature": false, "loaderror": 0, "overpower": false, "debug": 0, "update": { "status": "unknown", "has_update": false, "new_version": "", "old_version": "20230510-082920/v1.13.1-gda6f9f2" }, "ram_total": 49672, "ram_free": 37004, "fs_size": 233681, "fs_free": 116715, "uptime": 3 }`

Info packets duplicates informationd found on other MQTT paths. See nothing interesting here.

> Path: shellies/shellydimmer2-XXX/input_event/0 payload: `{ "event": "", "event_cnt": 0 }`

Already added
```
topic=%discovery_prefix%/select/%shelly_id%/input_event-0/config
payload={"name": "%shelly_id% Input Event 0", "json_attributes_topic": "~input_event/0", "value_template":"{{value_json.event}}" , "cmd_t": "~dummy", "frc_upd": "false", "enabled_by_default": true, "uniq_id": "%shelly_id%-event-0", "~": "shellies/%shelly_id%/", "dev_cla": "event", "stat_cla": "selector" , "ops":["-","S","L"] }
```

> Path: shellies/shellydimmer2-XXX/input_event/1 payload: `{ "event": "", "event_cnt": 0 }`

Already added
```
topic=%discovery_prefix%/select/%shelly_id%/input_event-1/config
payload={"name": "%shelly_id% Input Event 1", "json_attributes_topic": "~input_event/1", "value_template":"{{value_json.event}}" , "cmd_t": "~dummy", "frc_upd": "false", "enabled_by_default": true, "uniq_id": "%shelly_id%-event-1", "~": "shellies/%shelly_id%/", "dev_cla": "event", "stat_cla": "selector" , "ops":["-","S","L"] }
```

> Path: homeassistant/binary_sensor/shellydimmer2-XXX-online/config payload: `{ "name": "shellydimmer2-XXX Online", "stat_t": "~online", "uniq_id": "shellydimmer2-XXX-online", "~": "shellies/shellydimmer2-XXX/", "pl_on": "true", "pl_off": "false" }`

https://github.com/enesbcs/shellyteacher4domo/issues/17

**Comment by Xavier82** [comment]
My apology for the confusion.
I was checking and trying to match the devices created by Shelly MQTT Python script and the devices of ShellyTeacher4Domo and MQTT Explorer. For the completeness I wrote all paths.
I was removing the paths which were already added and then got disturbed and didn't finished the comment correctly.

The only thing is missing is a device called "shelly-XXX-0-lpush", I can't find this value in MQTT Explorer for this type of device but it was available in Shelly MQTT Python. 

I'm not missing this device myself but for the community/other users I wanted to make this as much as complete as I could.

So I think for now issue18 can be closed :)

**Comment by enesbcs** [comment]
> The only thing is missing is a device called "shelly-XXX-0-lpush", I can't find this value in MQTT Explorer for this type of device but it was available in Shelly MQTT Python.

Yes its available as ~longpush/0 according to Shelly docs, it can be added to the templates. However its also contained in Input Event selector.
