### ISSUE TITLE
Different subtype temp

### ISSUE THREAD

**Issue by Xavier82** [enesbcs/shellyteacher4domo#21]
Hi Alexander,

Using the MQTT Auto Discovery with ShellyTeacher4Domo, and now migrating from old Shelly python plugin to the MQTT Auto discovery.

Now I noticed that in the old Shelly Python plugin the temp was measured based on subtype "LaCrosse TX3".
In the new MQTT Auto Discovery with ShellyTeacher4Domo I see a device created for temp measurement on subtype "THR128/138,THC138".

![different subtype temp](https://github.com/enesbcs/shellyteacher4domo/assets/26725582/cae3f0f7-ffbb-4bbf-997f-fe3d968d5293)

The same I thing I see for the energy devices:
with old shelly Python Plugin I see a device to measure energy based on type "General" with subtype "kWh"
with MQTT auto Discovery woth ShellyTeacher4Domo  I see a device to measure energy based on type "General" with subtype "Custom Sensor".

![different subtype energy](https://github.com/enesbcs/shellyteacher4domo/assets/26725582/db73c89f-a1c5-49b9-9208-f49c581363f9)

Why is this? Why are they not the same?
Where is defined what the correct Type and Subtype should be?

**Comment by enesbcs** [comment]
With MQTT Autodiscovery, there is no possibility to choose the type and subtype of the device. It will be discovered and created by the Domoticz hardware based on the unit of measurement.
See:
https://github.com/domoticz/domoticz/blob/development/hardware/MQTTAutoDiscover.cpp#L1576

**Comment by enesbcs** [comment]
Latest Domoticz 2023 beta 15530 now supports Watt-hour and Watt-minute units, it is updated in the templates in commit
https://github.com/enesbcs/shellyteacher4domo/commit/3a2248fd39af8e2aee12bdbcf0280e6a8e5940f7
If you have problems with energy devices delete them from Domoticz and repeat the teaching process.

**Comment by Xavier82** [comment]
Thanks for this update!

At this moment I don't use beta versions.
I hope this will be available in new release.
I think for now this issue can be closed.

**Comment by enesbcs** [comment]
Yes, it will be available in the next stable release, thanks to gizmocuz!
Closing now.

**Comment by Xavier82** [comment]
Ok with this energy will be corrected. What about the temperature?
Is this also something which can be discussed with Gizmocuz?

**Comment by enesbcs** [comment]
> Ok with this energy will be corrected. What about the temperature? Is this also something which can be discussed with Gizmocuz?

There is only one option for temperature in MQTT Autodiscovery, what is the problem with this type? I do not see any drawback of either temperature sensor type.

**Comment by Xavier82** [comment]
I was just looking for differences during comparison between Shelly Python script and the Auto MQTT + ShellyTeacher.
Both are temp sensors and have the same values, this one I noticed.
