### ISSUE TITLE
Missing payload for GEN1 Shellyswitch 2.5 (SHSW-25) roller mode

### ISSUE THREAD

**Issue by Xavier82** [enesbcs/shellyteacher4domo#22]
Hi Alexander,

For shellyswitch25 (SHSW-25) in roller mode I don't see "roller pos" as device being created.

TOPIC: shellies/shellyswitch25-XXXX/roller/0/pos
Payload = VALUE

Can u have a look at that?

**Comment by enesbcs** [comment]
There is no such device.
"%shelly_id% Roller 0" is the only device which is created for a Gen1 roller, it has "pos_t" as roller/0/pos.

```
[SHSW-25-roller]   #Shelly 2 / Shelly 2.5 roller mode
topic=%discovery_prefix%/cover/%shelly_id%-roller-0/config
payload={"name": "%shelly_id% Roller 0", "cmd_t": "~roller/0/command", "stat_t": "~roller/0", "pos_t": "~roller/0/pos", "set_pos_t": "~roller/0/command/pos", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false", "json_attr_t": "~info", "pl_open": "open", "pl_cls": "close", "pl_stop": "stop", "stat_opening": "open", "stat_closing": "close", "pos_open": 100, "pos_clsd": 0, "uniq_id": "%shelly_id%-roller-0", "qos": 1, "~": "shellies/%shelly_id%/"}

```

Only Gen2 Cover devices has "roller pos" device (disabled by default), as Gen2 needs a fix to use position.

**Comment by Xavier82** [comment]
I saw that to, but in the old Shelly MQTT Python script I have a device called "shellyswitch25-XXXX-0-pos" AND a device called "shellyswitch25-XXXX-0-roller" with Auto MQTT and Shellyteacher I have only "shellyswitch25-XXX-roller-0", though bot have same function (opening, closed, stop and percentage). If there is no other different in feature/function then I guess only "shellyswitch25-XXX-roller-0" will do just fine.....

**Comment by enesbcs** [comment]
I do not work on the old plugin more than a year, but as i remember there are two distinct type in Domoticz Python framework: "Venetian Blinds " and "Blinds Percentage" the second one is able to handle positional movement, this is the reason i have implemented both.

In Domoticz MQTT Autodiscovery there are only one kind of Blind/Roller device.
I think its a positional one, as it handles the position topic.

**Comment by enesbcs** [comment]
Closed for inactivity
