### ISSUE TITLE
Cannot get Shelly H&T gen 2 online.

### ISSUE THREAD

**Issue by wapperp** [enesbcs/shellyteacher4domo#27]
Hello developper,

I have a shelly gen 2 h&t sensor (version with screen) and cannot get it online with the teacher en domoticz.
The teacher keeps telling that the device is "Online" (teacher running on rapberry), but it would not recognise and add the device to domoticz.

What to do?

Kind Regards

**Comment by enesbcs** [comment]
If the Teacher said the device is online, than it received an MQTT message through DEVID/online topic from device. (1st phase) It means they are talking to the same MQTT broker. Please double check that every MQTT option is enabled on your HT sensor, including RPC control. 
Did you watch the tutorial video, especially the settings at 1:27? ( https://www.youtube.com/watch?v=3PvYhFIsVN4&t=87s )
If the device does not respond to the Shelly.GetConfig command, than it will never be added, as its the 2nd phase of detection.

Please use the console/command line Teacher for reporting errors and enable Debug option to see messages!

**Comment by wapperp** [comment]
Hello developper,

I have seen the tutorial, but forgot to check the MQTT option RPC control. After ticking this checkbox the teacher found the device and it was added to Domoticz. Note that you have to wait to an temperature update from the sensor with the teacher on to receive the temperature and humidity sensor. Otherwise you will have 2 kind of switches only. Thanx for your help, it works now :-).

Kind regards!
