### ISSUE TITLE
Shelly addon temperature and voltmeter reporting

### ISSUE THREAD

**Issue by naeblizz** [enesbcs/shellyteacher4domo#28]
Hi. I have installed the Shelly addon with 3 ds18b20 sensors and a analog input voltmeter. The addon is attached to my Shellyplus2pm device. From what I can see in docs the addon is not supported yet by the teacher? The input and output relays works perfecly  after I upgraded version of the teacher. I can see 2 temperature readings in domoticz attached to the Shelly2PM , but they are not reporting the readings of the ds18b20 sensors. I suspect I have to change some things in the mqtt_templates_gen2 file to get it working ? I can see the right values of the temperature sensors in MQTT explorer. Maybe you can see in my pictures what I need to change to get it working?
![Shellytemp](https://github.com/enesbcs/shellyteacher4domo/assets/106927378/24e56209-e7fa-489d-8e94-5aefe95c0e70)
![Shelly domo](https://github.com/enesbcs/shellyteacher4domo/assets/106927378/91ccb26c-d240-4fbb-a1d4-c1746113e2ec)

**Comment by enesbcs** [comment]
You are right, i had no idea - until today - what MQTT topics are used by the Gen2 Shelly addons.. as the Gen2 official docs are not so clear.
Yep, it has to be added to mqtt_templates_gen2.txt, using the HA config language... like this:

```
topic=%discovery_prefix%/sensor/%shelly_id%-ext-0/temperature/config
payload={"name": "%shelly_id% Temperature Ext0", "enabled_by_default": false, "uniq_id": "%shelly_id%-temperature-100", "qos": 0, "~":"%shelly_topic%/", "dev_cla": "temperature", "stat_cla": "measurement", "unit_of_meas": "°C","stat_t": "~status/temperature:100", "val_tpl": "{{ value_json.tC }}", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false"}
```

I will add these to github, as i see the Addon can be used with Shelly Plus 1/1PM , Shelly Plus 2PM, Shelly Plus i4/i4DC.

**Comment by enesbcs** [comment]
Added at commit https://github.com/enesbcs/shellyteacher4domo/commit/b24524b259e634b111cc70296fabdaf4c21cd4c7

**Comment by naeblizz** [comment]
Thanks alot , Tested and  works perfectly now .

**Comment by enesbcs** [comment]
Thanks for testing!
