### ISSUE TITLE
teacher4 crashes with Shelly EM

### ISSUE THREAD

**Issue by Emarc67** [enesbcs/shellyteacher4domo#29]
Hi, first, thanks for your great work about shelly and domoticz !
I'm triing to migrate my shellyes from ShellyMQTT to MQTTautoDiscovery, using teacher4. It works fine for ShellyplusHT (gen2) and Shellymotionsensor (gen1), but crashes with my 2 shellyEM.
Here the error message:
>>>GEN1 device 192.168.1.46 SHEM shellyem-daikin found
Traceback (most recent call last):
  File "shellyteacher4domo.py", line 620, in <module>
    mqttstr = {"topic": fill_template_str(mt[i]['topic'], di),"payload": fill_template_str(mt[i]['payload'], di)}
KeyError: 'topic'
The view in Mqtt-explorer:
shellies/shellyem-daikin/info
{"wifi_sta":{"connected":true,"ssid":"Freebox_THQUBC","ip":"192.168.1.46","rssi":-73},"cloud":{"enabled":false,"connected":false},"mqtt":{"connected":true},"time":"12:23","unixtime":1696501424,"serial":1,"has_update":false,"mac":"F4CFA2E45677","cfg_changed_cnt":0,"actions_stats":{"skipped":0},"relays":[{"ison":false,"has_timer":false,"timer_started":0,"timer_duration":0,"timer_remaining":0,"overpower":false,"is_valid":false,"source":"input"}],"emeters":[{"power":0.00,"reactive":0.00,"pf":0.00,"voltage":0.00,"is_valid":false,"total":834608.6,"total_returned":12.4},{"power":0.00,"reactive":0.00,"pf":0.00,"voltage":0.00,"is_valid":false,"total":333837.1,"total_returned":0.0}],"update":{"status":"unknown","has_update":false,"new_version":"","old_version":"20230913-114150/v1.14.0-gcb84623"},"ram_total":51064,"ram_free":36368,"fs_size":233681,"fs_free":156122,"uptime":2}
![image](https://github.com/enesbcs/shellyteacher4domo/assets/16455124/a51619c3-5050-4391-9787-fc56fd4bac7a)

thank you in advance for your help !

**Comment by enesbcs** [comment]
You are right. It seems that i forgot to add topic to the ShellyEM template, when i added undocumented PowerFactor attributes. Fixed in commit https://github.com/enesbcs/shellyteacher4domo/commit/529f6378aa5a6424530c90dbc2a92f10bda758a9

Please try it again with the latest version online.

**Comment by Emarc67** [comment]
tested with 2 shellyEM, works fine :-)
Thank you !
