### ISSUE TITLE
Issue with MQTT energy value on ShellyPro4PM

### ISSUE THREAD

**Issue by Xavier82** [enesbcs/shellyteacher4domo#31]
Hi Alexander,

Today I discovered with MQTT Explorer that there is an issue with the Topic of homeassistant/sensor/shellypro4pm-XXXX-3/energy/config

the values are:
`{
  "name": "shellypro4pm-XXXX-Energy 3",
  "stat_t": "~status/switch:3",
  "frc_upd": "false",
  "uniq_id": "shellypro4pm-XXXX-2-energy",
  "qos": 0,
  "~": "shellypro4pm-XXXX/",
  "dev_cla": "energy",
  "stat_cla": "total_increasing",
  "unit_of_meas": "Wh",
  "val_tpl": "{{ value_json['aenergy'].total }}",
  "device": {
    "identifiers": [
      "XXXX-3"
    ],
    "manufacturer": "Shelly",
    "model": "shellypro4pm",
    "name": "shellypro4pm-XXXX-3"
  }
}`

As you can see the value uniq_id refers to "shellypro4pm-XXXX-2-energy" which of course should be "shellypro4pm-XXXX-3-energy"

At first I thought it was an issue in the MQTT template (Gen2), So I fixed the value from 2 to 3.
After rebooting the shelly device the shellyteacher4domo didn't find the energy 3 device, so I used MQTT Explorer and found out that the issue is on the Shelly MQTT side.

So I created a support ticket for this at Shelly.Cloud company.
(Reaction time is 72 hours)

In advance you already might update the MQTT_Templates_gen2.txt file with this.

**Comment by enesbcs** [comment]
> Hi Alexander,
> 
> Today I discovered with MQTT Explorer that there is an issue with the Topic of homeassistant/sensor/shellypro4pm-XXXX-3/energy/config
> 
> the values are: `{ "name": "shellypro4pm-XXXX-Energy 3", "stat_t": "~status/switch:3", "frc_upd": "false", "uniq_id": "shellypro4pm-XXXX-2-energy", "qos": 0, "~": "shellypro4pm-XXXX/", "dev_cla": "energy", "stat_cla": "total_increasing", "unit_of_meas": "Wh", "val_tpl": "{{ value_json['aenergy'].total }}", "device": { "identifiers": [ "XXXX-3" ], "manufacturer": "Shelly", "model": "shellypro4pm", "name": "shellypro4pm-XXXX-3" } }`
> 
> As you can see the value uniq_id refers to "shellypro4pm-XXXX-2-energy" which of course should be "shellypro4pm-XXXX-3-energy"
> 
> At first I thought it was an issue in the MQTT template (Gen2), So I fixed the value from 2 to 3. After rebooting the shelly device the shellyteacher4domo didn't find the energy 3 device, so I used MQTT Explorer and found out that the issue is on the Shelly MQTT side.
> 
> So I created a support ticket for this at Shelly.Cloud company. (Reaction time is 72 hours)
> 
> In advance you already might update the MQTT_Templates_gen2.txt file with this.

You are right its my bad, fixed the template in actual ShellyTeacher release.

I think you should delete both energy-2 and energy-3 device from Domoticz and rerun the Teacher to reteach them.

**Comment by Xavier82** [comment]
I don't think it's your bad......
The payload itself is wrong, checked it in MQTT Explorer. I created a support ticket at Shelly, they are investigating this...
I will come back to u when I get the feedback of Shelly.

**Comment by Xavier82** [comment]
In MQTT Explorer I see the following values:
TOPIC:
`shellypro4pm-XXX/online`
VALUE:
`false`

TOPIC:
`shellypro4pm-XXX/events/rpc`
VALUE:
`{"src":"shellypro4pm-XXX","dst":"shellypro4pm-XXX/events","method":"NotifyStatus","params":{"ts":1699032240.20,"switch:3":{"id":3,"aenergy":{"by_minute":[0.000,0.000,0.000],"minute_ts":1699032239,"total":0.000}}}}`

TOPIC:
`shellypro4pm-XXX/status/switch:0`
VALUE:
`{"id":0, "source":"loopback", "output":false, "apower":0.0, "voltage":231.0, "freq":50.0, "current":0.000, "pf":0.00, "aenergy":{"total":0.000,"by_minute":[0.000,0.000,0.000],"minute_ts":1699032299},"temperature":{"tC":24.0, "tF":75.3}}`

TOPIC:
`shellypro4pm-XXX/status/switch:1`
VALUE:
`{"id":1, "source":"loopback", "output":false, "apower":0.0, "voltage":231.2, "freq":50.0, "current":0.000, "pf":0.00, "aenergy":{"total":0.000,"by_minute":[0.000,0.000,0.000],"minute_ts":1699032359},"temperature":{"tC":23.9, "tF":75.1}}`

TOPIC:
`shellypro4pm-XXX/status/switch:2`
VALUE:
`{"id":2, "source":"loopback", "output":false, "apower":0.0, "voltage":231.4, "freq":50.0, "current":0.000, "pf":0.00, "aenergy":{"total":0.000,"by_minute":[0.000,0.000,0.000],"minute_ts":1699032359},"temperature":{"tC":23.9, "tF":75.1}}`

TOPIC:
`shellypro4pm-XXX/status/switch:3`
VALUE:
`{"id":3, "source":"loopback", "output":false, "apower":0.0, "voltage":230.9, "freq":50.0, "current":0.000, "pf":0.00, "aenergy":{"total":0.000,"by_minute":[0.000,0.000,0.000],"minute_ts":1699032419},"temperature":{"tC":23.9, "tF":75.1}}`

TOPIC:
`shellies/shellypro4pm-XXX/announce`
VALUE:
`{"name":"Shelly 4PM Pro v2","id":"shellypro4pm-XXX","mac":"XXX","slot":0,"model":"SPSW-104PE16EU","gen":2,"fw_id":"20231031-152251/1.0.7-g5db02bd","ver":"1.0.7","app":"Pro4PM","auth_en":true,"auth_domain":"shellypro4pm-XXX"}`

TOPIC:
`shellies/shellypro4pm-XXX/relay/0/energy`
VALUE:
`0`

TOPIC:
`shellies/shellypro4pm-XXX/relay/0/power`
VALUE:
`2e-7`

TOPIC:
`shellies/shellypro4pm-XXX/relay/1/energy`
VALUE:
`0`

TOPIC:
`shellies/shellypro4pm-XXX/relay/1/power`
VALUE:
`2e-7`

TOPIC:
`shellies/shellypro4pm-XXX/relay/2/energy`
VALUE:
`0`

TOPIC:
`shellies/shellypro4pm-XXX/relay/2/power`
VALUE:
`2e-7`

TOPIC:
`shellies/shellypro4pm-XXX/relay/3/energy`
VALUE:
`0`

TOPIC:
`shellies/shellypro4pm-XXX/relay/3/power`
VALUE:
`2e-7`

**Comment by enesbcs** [comment]
> In MQTT Explorer I see the following values: TOPIC: `shellypro4pm-XXX/online` VALUE: `false`
> 
You find the reason in the first value: "/online" value should be 'true' when the device is connected, and only true is accepted by ShellyTeacher. Other values are automatically discarded.
https://github.com/enesbcs/shellyteacher4domo/blob/0824d39b1513a6d385856f182a44601a4de8d2d9/shellyteacher4domo.py#L164

https://shelly-api-docs.shelly.cloud/gen2/0.14/ComponentsAndServices/Mqtt/#step-7-subscribe-for-messages-on-connecting-and-disconnecting-over-mqtt

Please try to disable MQTT then enable again on this shelly unit. If this wont help, do a factory reset.

**Comment by Xavier82** [comment]
Thanks, disabled and revbooted Shelly and then enabled again and rebooted MQTT but no fix.
Still waiting on Shelly Support, Factory reset is last thing I will because if it is a issue in the firmware I need to reconfigure the ShellyPro4PM again.....

Please standby....I will contact again if Shelly support has contacted me.

**Comment by enesbcs** [comment]
I think they will also propose the factory reset but i will be curious as your unit behaves very peculiarly.

**Comment by Xavier82** [comment]
A new firmware 1.0.8 has been released, after upgrading MQTT became online again.

Based on your adjustment in "mqtt_templates_gen2.txt" the energy-3 became available now also after Shelly fixed this in the new 1.0.8 release.
