### ISSUE TITLE
Shelly addon temperature with shelly1 / shelly1PM not seen by user

### ISSUE THREAD

**Issue by Emarc67** [enesbcs/shellyteacher4domo#32]
Hi Alexander,
The Shelly1PM reports its internal temperature to Domoticz, but not the external temp. provided by the addon.
The shelly1 reports nothing about temperature.
Would it be possible for you to correct the template file ?
Thanks in advance !
Marc

![MQTT_explorer_shelly1_shelly1PM](https://github.com/enesbcs/shellyteacher4domo/assets/16455124/7269a973-0e3a-469f-8bf0-05b08d0ee512)

**Comment by enesbcs** [comment]
Shelly1 and Shelly1PM ext_temperature/0 already implemented, please enable it in Domoticz device list first:

You can find them in mqtt_templates.txt

```
[SHSW-1]  # Shelly 1
topic=%discovery_prefix%/sensor/%shelly_id%-ext-0/temperature/config
payload={"name": "%shelly_id% Temp 0", "stat_t": "~ext_temperature/0", "enabled_by_default": false, "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false", "uniq_id": "%shelly_id%-temp-0", "~": "shellies/%shelly_id%/", "unit_of_meas":"°C","device_class":"temperature","device": {"identifiers": ["%shelly_mac%-temp0"],"manufacturer": "Shelly","model": "%shelly_model%","name": "%shelly_id%-temp0"}}

[SHSW-PM]  # Shelly 1 PM
topic=%discovery_prefix%/sensor/%shelly_id%-ext-0/temperature/config
payload={"name": "%shelly_id% Temp 0", "stat_t": "~ext_temperature/0", "enabled_by_default": false,"avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false", "uniq_id": "%shelly_id%-temp-0", "~": "shellies/%shelly_id%/", "unit_of_meas":"°C","device_class":"temperature","device": {"identifiers": ["%shelly_mac%-temp0"],"manufacturer": "Shelly","model": "%shelly_model%","name": "%shelly_id%-temp0"}}
```

Double check if you are using the latest mqtt_templates.txt and try to re-teach your Shelly1 and Shelly1PM if you do not see the device in Domoticz - they wont appear until the first measurement arrives to Domo.

**Comment by enesbcs** [comment]
Closed as no feedback
