### ISSUE TITLE
shellyteacher 4 installation with raspberry os Bookworm

### ISSUE THREAD

**Issue by Emarc67** [enesbcs/shellyteacher4domo#33]
Hi Alexander, my "test raspberry" runs with linux v12 64bits desktop edition.  Below, a report of the installation of  Shellyteacher 4:
sudo apt install python3-pip git  : OK  
python3-pip is already the most recent version (23.0.1+dfsg-1+rpt1) / same for git
sudo pip3 install paho-mqtt :
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.

I'm by far not a linux expert, so I tried something more easyer ;-) With the Add / remove software (PI desktop ) I installed python3-paho-mqtt 1.6.1-1, and the installation works ! 

python3 shellyteacher4domo.py :
TKInter init failed no display name and no $DISPLAY environment variable
Ini file exists
Connecting to MQTT server...
Connection failed to MQTT server at **192.168.1.2** [Errno 111] Connection refused
MQTT connection failed, alter settings and retry!

My MQTT server (mosquitto) has the IP 192.168.1.3 . After correction of settings.py, shellyteacher4 starts.

Did I something wrong, or the installation code needs to be changed ?

Thanks for your work
Regards
Marc

**Comment by enesbcs** [comment]
In case you are using Debian 12, please remove 'EXTERNALLY-MANAGED' file from your system to be able to use pip3. https://www.jeffgeerling.com/blog/2023/how-solve-error-externally-managed-environment-when-installing-pip3

Otherwise you can force to install paho-mqtt in that way:
`sudo pip3 install paho-mqtt --break-system-packages`

**Comment by enesbcs** [comment]
> I'm by far not a linux expert, so I tried something more easyer ;-) With the Add / remove software (PI desktop ) I installed python3-paho-mqtt 1.6.1-1, and the installation works !

Yep, installation by the package manager will also work.

But if you are a windows user, why dont you simply use the windows binary of the Teacher?

**Comment by enesbcs** [comment]
Closed as no answer
