### ISSUE TITLE
Some errors running teacher

### ISSUE THREAD

**Issue by MikeyMan83** [enesbcs/shellyteacher4domo#34]
Hi! 

I'm having some errors running the teacher on a pi:

```
PuTTY X11 proxy: unable to connect to forwarded X server: Network error: Connection refused
PuTTY X11 proxy: unable to connect to forwarded X server: Network error: Connection refused
TKInter init failed couldn't connect to display "localhost:10.0"
Ini file exists
Connecting to MQTT server...
Connecting to MQTT server...
Connecting to MQTT server...
Starting eval loop, waiting Shelly devices to appear on MQTT announce... press CTRL-C to cancel

```

settings seem to be correct. Although i'm wondering about the different usage of ' , "  and no brackets around the port.

```
data = { }
# -----------------------------------------------
# WARNING: If .ini file exists it will overwrite the default values below!
# -----------------------------------------------
data['mqtt_ip'] = '10.0.0.4' # mqtt server ip
data['mqtt_port'] = 1883        # mqtt server port
data['mqtt_user'] = ""          # mqtt server username
data['mqtt_pass'] = ""          # mqtt server password
data['discovery_prefix'] = 'shellies' # autodiscovery prefix for Domoticz
testrun = False
retain  = True   # if retain is True, config template will be saved onto mqtt broker permanently
gen1    = True  # enable Gen1 device detection
gen2    = True   # enable Gen2 device detection
debug   = False   # print debug messages if True
# -----------------------------------------------
# DO NOT MODIFY LINES BELOW, UNLESS YOU ARE ABSOLUTELY SURE WHAT YOU ARE DOING!
# -----------------------------------------------
data['trigger_topic1'] = "shellies/announce"      #gen1 device detection
data['trigger_topic2'] = "shellies_discovery/rpc" #gen2 device reply
data['trigger_topic3'] = "+/online"               #gen2 device detection
data['gen1_template_file'] = 'mqtt_templates.txt'
data['gen2_template_file'] = 'mqtt_templates_gen2.txt'
# -----------------------------------------------
## SYSTEM VARIABLES, DO NOT TOUCH!
# -----------------------------------------------
shque = []
shjsons = {}
mqttsender = []

```

Any thoughts?

**Comment by enesbcs** [comment]
> Hi!
> 
> I'm having some errors running the teacher on a pi:
> 
> ```
> PuTTY X11 proxy: unable to connect to forwarded X server: Network error: Connection refused
> PuTTY X11 proxy: unable to connect to forwarded X server: Network error: Connection refused
> TKInter init failed couldn't connect to display "localhost:10.0"

You can run teacher with command line parameter -c and GUI errors wont appear. GUI was not intended to work through SSH,  GUI is for folks who are using a real Linux Desktop with an attached monitor. Like me. If you are using a Windows desktop, you can use the precompiled Windows binary as it is written in the Readme.

> Ini file exists
> Connecting to MQTT server...
> Connecting to MQTT server...
> Connecting to MQTT server...
> Starting eval loop, waiting Shelly devices to appear on MQTT announce... press CTRL-C to cancel
> ```

I see no problem here. Teacher are connected to the MQTT server and awaiting announcement messages from the Shelly devices, which are already configured to connect to the same MQTT, as you must have seen in the video.

> settings seem to be correct. Although i'm wondering about the different usage of ' , " and no brackets around the port.

Fortunately Python does not care if it is ' or ". Port is an integer and not a string.

> 
> ```
> data = { }
> # -----------------------------------------------
> # WARNING: If .ini file exists it will overwrite the default values below!
> # -----------------------------------------------
> data['mqtt_ip'] = '10.0.0.4' # mqtt server ip
> data['mqtt_port'] = 1883        # mqtt server port
> data['mqtt_user'] = ""          # mqtt server username
> data['mqtt_pass'] = ""          # mqtt server password
> data['discovery_prefix'] = 'shellies' # autodiscovery prefix for Domoticz
> testrun = False
> retain  = True   # if retain is True, config template will be saved onto mqtt broker permanently
> gen1    = True  # enable Gen1 device detection
> gen2    = True   # enable Gen2 device detection
> debug   = False   # print debug messages if True
> # -----------------------------------------------
> # DO NOT MODIFY LINES BELOW, UNLESS YOU ARE ABSOLUTELY SURE WHAT YOU ARE DOING!
> # -----------------------------------------------
> data['trigger_topic1'] = "shellies/announce"      #gen1 device detection
> data['trigger_topic2'] = "shellies_discovery/rpc" #gen2 device reply
> data['trigger_topic3'] = "+/online"               #gen2 device detection
> data['gen1_template_file'] = 'mqtt_templates.txt'
> data['gen2_template_file'] = 'mqtt_templates_gen2.txt'
> # -----------------------------------------------
> ## SYSTEM VARIABLES, DO NOT TOUCH!
> # -----------------------------------------------
> shque = []
> shjsons = {}
> mqttsender = []
> ```
> 
> Any thoughts?

Looks fine.

**Comment by enesbcs** [comment]
closed as no reply
