### ISSUE TITLE
Shelly1PM only sees one external temperature sensor

### ISSUE THREAD

**Issue by hkhk12** [enesbcs/shellyteacher4domo#36]
Just started using shellyteacher4domo and noticed that it only sees one external temp sensor when two are connected to a Shelly1PM.
In my case it only sees shelly1pm-XXXXXXXXXX-temp-1 and shelly1pm-XXXXXXXXXXXX-temperature (which is the device temp).
I have two shelly1PM's both with two external temp sensors. Both act the same.
Used latest shellyteacher4domo  and latest domoticz beta.
All other devices (Shelly1, Shelly2, Shelly2.5, ShellyDimmer, ShellyDimmer2 and ShellyPlus1PM) work fine.

**Comment by enesbcs** [comment]
Configuration objects and MQTT data needed for debugging.

First two external temperature sensor data should arrive into  "~ext_temperature/0" and "~ext_temperature/1"

Until no data arrives, than temp-0 will not be created by Domoticz, but you should see these objects in your MQTT server:
%discovery_prefix%/sensor/%shelly_id%-ext-0/temperature/config
%discovery_prefix%/sensor/%shelly_id%-ext-1/temperature/config

**Comment by hkhk12** [comment]
Thanks for your reply,

Please tell me what I need to send.
Attached info from MQTT explorer if that helps (although I see no temp values in there).
[shellyMQTT.zip](https://github.com/enesbcs/shellyteacher4domo/files/13591178/shellyMQTT.zip)

**Comment by enesbcs** [comment]
Your shelly1pm-XXXXXXXXXXXX-ext-0/temperature/config either has a non-valid "stat_t" entry or this shellyMQTT.txt file you just send has serious mistakes.
Try to download latest ShellyTeacher 0.6, delete Shelly1PM temperature sensors from Domoticz (ONLY temperature sensors!, reboot Domoticz to forget devices, and run shellyteacher after reboot completed.

If this not helps, show me MQTT data from these paths:
- shellies/shelly1pm-XXXXXXXXXXXX/ext_temperature/0
- shellies/shelly1pm-XXXXXXXXXXXX/ext_temperature/1

and double check that the above paths are in their correct config objects:
- homeassistant/shelly1pm-XXXXXXXXXXXX-ext-0/temperature/config
- homeassistant/shelly1pm-XXXXXXXXXXXX-ext-1/temperature/config

**Comment by hkhk12** [comment]
Unfortunately no change. I even went to delete the complete device from domoticz and entries via MQTT explorer from mosquitto (both in /shellies and /homeassistent.

![image](https://github.com/enesbcs/shellyteacher4domo/assets/45298864/a17d5dca-74e1-4f2b-a9c6-64fdbbe0457d)

Hope the screenshot is informative enough. Otherwise please advice how to export.

**Comment by enesbcs** [comment]
I see. These are the interesting lines from your MQTT data:

Data:
shellies/shelly1pm-ID/ext_temperature/0 = 33.6
shellies/shelly1pm-ID/ext_temperature/1 = 35.5

Configuration objects:
```
homeassistant/shelly1pm-ID/ext-0/temperature
{"name": shelly1pm-ID Temp 0", "stat_t": "~ext_temperature/0", "enabled_by_default": false, ,"avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false", "uniq_id": "shelly1pm-ID-temp-0", "~": "shellies/shelly1pm-ID/", "unit_of_meas":"C","device_class":"temperature","device": {"identifiers": ["ID-temp0"],"manufacturer": "Shelly","model": "%shelly_model%","name": "ID-temp0"}}

homeassistant/shelly1pm-ID/ext-0/humidity
{"name": shelly1pm-ID Temp 0", "stat_t": "~ext_humidity/0", "enabled_by_default": false, ,"avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false", "uniq_id": "shelly1pm-ID-hum", "~": "shellies/shelly1pm-ID/", "unit_of_meas":"%","device_class":"humidity","device": {"identifiers": ["ID-temp0"],"manufacturer": "Shelly","model": "%shelly_model%","name": "ID-temp0"}}

homeassistant/shelly1pm-ID/ext-1/temperature
{"name": shelly1pm-ID Temp 0", "stat_t": "~ext_temperature/1", "enabled_by_default": false, ,"avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false", "uniq_id": "shelly1pm-ID-temp-0", "~": "shellies/shelly1pm-ID/", "unit_of_meas":"C","device_class":"temperature"}
```

Although there is some strange characters behind "C" unit, i guess this is not a problem, as temp1 is working. Otherwise everything looks correct. What is your Domoticz version?

**Comment by hkhk12** [comment]
Domoticz version:
Version: 2023.2 (build 15697).
Compile Date: 2023-12-04 13:03:46

**Comment by enesbcs** [comment]
You are right, tested with latest Domoticz beta. The Temp0 device is bind with Humidity, and Domoticz awaits humidity before displaying temperature, but you are using a sensor which only report temperature.
To workaround this, i have added an extra Temp0-S single sensor which is only uses temperature. Added at commit https://github.com/enesbcs/shellyteacher4domo/commit/e379750f074a165cb135dcbc7fbf39d1a6404805

Could you please download [mqtt_templates.txt](https://raw.githubusercontent.com/enesbcs/shellyteacher4domo/e379750f074a165cb135dcbc7fbf39d1a6404805/mqtt_templates.txt) into the directory where your ShellyTeacher is downloaded, overwrite older .txt and teach again the Shelly1PM?

**Comment by hkhk12** [comment]
Thanks Alexander. 
That fixed it.
