### ISSUE TITLE
shelly 1 mini (device support)

### ISSUE THREAD

**Issue by jurgenvdven** [enesbcs/shellyteacher4domo#37]
Hi!

I'm using a shelly 1 mini (gen2), but it seems that it is not supported with shellyteacher.

---ERROR: GEN2 device shelly1mini-xxxxxx shelly1mini-xxxxxxx template not found

Do we expect this device will be supported in the future?

Thank you.

**Comment by enesbcs** [comment]
Gen2 Shelly1 Mini support added at 2023.11.01

Please download latest template file to you ShellyTeacher directory.
https://raw.githubusercontent.com/enesbcs/shellyteacher4domo/main/mqtt_templates_gen2.txt

**Comment by jurgenvdven** [comment]
I updated the template file and the shelly is added to domoticz.

However the "output" switch is not listed under switches and devices.

only:  Online, relay, input, event

None of these can toggle the output on or off.

Any idea?

**Comment by jurgenvdven** [comment]
nevermind. Just forgot to generic status update setting.

thanks!
