### ISSUE TITLE
Shelly plus i4 with Tasmota firmware

### ISSUE THREAD

**Issue by AHeuvelman** [enesbcs/shellyteacher4domo#4]
Hello Alexander Nagy, aka enebcs,

I recently bought a Shelly plus i4 and set up Tasmota here so I could integrate it into domoticz but I see it's not in your script yet, is it possible you could also add the Shelly plus i4 in the Shellyteach4domo you made because I don't see it listed yet.
I also installed MQTT and Tasmoticz.

I hope to hear from you

Thank you in advance,

Regards Arie Heuvelman,
The Netherlands

**Comment by enesbcs** [comment]
Its possible, although i need to know the MQTT payload of this device, but i do not have one for testing.
I guess the inputs reported in this form: (not sure)

shellyID/status/input:0 {"id":0,"state":false}
shellyID/status/input:1 {"id":0,"state":false}
shellyID/status/input:2 {"id":0,"state":false}
shellyID/status/input:3 {"id":0,"state":false}

but i have no idea about how short/long/double push differences reported.

Can you check it with MQTT Explorer?

**Comment by enesbcs** [comment]
> I recently bought a Shelly plus i4 and set up Tasmota here so I could integrate it into domoticz but I see it's not in 

This script is for factory Shelly firmware only.

On Tasmota you need to enable: Setoption19 1

>SetOption19 | Set Home Assistant discovery protocol.
>0 = use Tasmota integration (default)
>1 = use MQTT discovery

Its not related to Shelly... but Tasmota integration is the default in newer versions, which is not supported in Domoticz. Please check Tasmota documentation and Tasmota issues, if you have related questions.

**Comment by AHeuvelman** [comment]
Oke, thanks for your answer.

 I look further.

Thanks again.

Greetings,

A. Heuvelman.

Op do 16 feb. 2023 07:10 schreef Alexander Nagy ***@***.***>:

**Comment by enesbcs** [comment]
> Oke, thanks for your answer. I look further. Thanks again. Greetings, A. Heuvelman. Op do 16 feb. 2023 

In case you manage to flash back factory shelly firmware to the i4, i am sure we can make it work.

**Comment by AHeuvelman** [comment]
Hi Alexander,

I'am going to flash the original firmware for the shelly plus i4.
I will do that after my holiday, then I will contact you for further
assistance.

Thank you in advance,

Arie Heuvelman,
The Netherlands.


Op zo 19 feb. 2023 om 17:02 schreef Alexander Nagy ***@***.***

**Comment by enesbcs** [comment]
Please feel free to reopen this issue when ready to proceed.

**Comment by AHeuvelman** [comment]
Hi Alexander,

I have now put the correct firmware on the i4 and saw that you have already
added it.
I could now also integrate it into domoticz and I think it works perfectly
well.
Anyway thanks for your support, if I have any problems in the future I will
report back.

Yours sincerely,

Arie Heuvelman,
The Netherlands

Op vr 24 feb 2023 om 07:04 schreef Alexander Nagy ***@***.***
