### ISSUE TITLE
Can this be run in Docker?

### ISSUE THREAD

**Issue by sincze** [enesbcs/shellyteacher4domo#41]
I would be delighted if we could run this in a Docker.

<img width="605" alt="image" src="https://github.com/enesbcs/shellyteacher4domo/assets/5776333/09424815-2efa-44a9-acab-e9fb7d94c696">

Version now running 0.6 in a docker.
https://hub.docker.com/repository/docker/sincze/shellyteacher4domo/general

**Comment by enesbcs** [comment]
Nice, however i still recommend running the precompiled binary for simple users without linux knowledge.

**Comment by sincze** [comment]
I agree with @enesbcs and tested this morning. Just running the file **once** with Shelly powered up will give the expected result.

**Comment by sincze** [comment]
I agree with @enesbcs and tested this morning. Just running the file **once** with Shelly powered up will give the expected result.
