### ISSUE TITLE
Switches merged into one

### ISSUE THREAD

**Issue by zzattack** [enesbcs/shellyteacher4domo#43]
It seems that all my gen2 shelly plus 2pm switches somehow merge into one. Whenever I use domoticz to switch relay 0 of any of my 4 devices, the relay 0 output of the other 3 toggles as well. When operating relay 1, the others change on relay 1 as well. They all have unique device ids and the issue persists even after clearing mosquito.db and the mqtt auto discovery hardware in domoticz. Gen1 and my single relay gen2 devices appear unaffected.

**Comment by enesbcs** [comment]
Please add some example device names and ID's which operates at the same time, and at least two configuration objects of them.
It has to be under this topic:
`%discovery_prefix%/switch/shellyplus2pm-xxxxx-0/config`
`%discovery_prefix%/switch/shellyplus2pm-xxxxx-1/config`

Did you changed the shelly default prefix on them?
The most interesting part of the template is at the end "~": "%shelly_topic%/" if the topics are the same, they operate  at the same time. I have no other idea.

**Comment by zzattack** [comment]
I've cleared all caches, mosquitto.db, reset and updated the fw on the shelly switches and the problem has gone away. I assume it's unlikely to be related to the teacher.
