### ISSUE TITLE
Support for Shelly Pro EM-50

### ISSUE THREAD

**Issue by spamajor** [enesbcs/shellyteacher4domo#44]
Hi, I have the Shelly Pro EM-50 and was wondering if/how I can help make a template available for this Shelly as well. Thanx in advance

Screenshot MQTT explorer:
![image](https://github.com/enesbcs/shellyteacher4domo/assets/50380889/36bcc454-e570-4a87-8d13-5dc42cc26533)

**Comment by enesbcs** [comment]
Thank you for the samples it seems very similar to earlier EM devices, it just have an em1 tag inline.

You can test it if you download latest database to your shellyteacher program from github:
https://raw.githubusercontent.com/enesbcs/shellyteacher4domo/main/mqtt_templates_gen2.txt

**Comment by spamajor** [comment]
[cid:adf61595-2865-4196-87ca-1e986118f0d5]

You fixed that quickly! I also tested it a bit and it picks it up just fine. Thanx!

________________________________
Van: Alexander Nagy ***@***.***>
Verzonden: donderdag 25 januari 2024 07:38
Aan: enesbcs/shellyteacher4domo ***@***.***>
CC: spamajor ***@***.***>; Author ***@***.***>
Onderwerp: Re: [enesbcs/shellyteacher4domo] Support for Shelly Pro EM-50 (Issue #44)


Thank you for the samples it seems very similar to earlier EM devices, it just have an em1 tag inline.

You can test it if you download latest database to your shellyteacher program from github:
https://raw.githubusercontent.com/enesbcs/shellyteacher4domo/main/mqtt_templates_gen2.txt
