### ISSUE TITLE
Request to implement Shellyplus Smoke

### ISSUE THREAD

**Issue by Quax1507** [enesbcs/shellyteacher4domo#46]
I have some Shellyplus Smoke detectors which are not supported.
Could You please implement them?

Thanks Quaxx1507

**Comment by enesbcs** [comment]
Yep, fortunately the device itself is not so complicated, however i do not really like the Gen2 device documentation, Gen1 was way much better to understand.

Based on this article:
https://shelly-api-docs.shelly.cloud/gen2/ComponentsAndServices/Smoke
i guess this device sends data through /status/smoke:0 topic, you can download latest database from testing branch here:

https://raw.githubusercontent.com/enesbcs/shellyteacher4domo/testing/mqtt_templates_gen2.txt

**Comment by Quax1507** [comment]
Wow! That was fast :-)
I can confirm it is working.
Many thanks!
