### ISSUE TITLE
MIgration to paho-mqtt version 2.0 (if you encounter error: TypeError: Client.__init__() missing 1 required positional argument: 'callback_api_version')

### ISSUE THREAD

**Issue by malgeri** [enesbcs/shellyteacher4domo#47]
Hi,

first of all thanks for your code!

I have installed it on my ubuntu box running python3.10. The preinstall.sh automatically installs the latest version of paho-mqtt (version 2.0) that is incompatible with the current  shellyteacher4domo.py. Details can be found in https://eclipse.dev/paho/files/paho.mqtt.python/html/migrations.html).

The easy solution is to change all instances of: 
MQTTClient() into MQTTClient(mqtt.CallbackAPIVersion.VERSION1)
and 
MQTTClientOnlineCheck() into MQTTClientOnlineCheck(mqtt.CallbackAPIVersion.VERSION1)

in the connect_mqtt() function.

Hope this can be useful to others in my same situation.

Regards,
                   l.

**Comment by enesbcs** [comment]
Thank you for your work!

Support added at commit:
https://github.com/enesbcs/shellyteacher4domo/commit/bea8627c7369b5e60629c0d888edd4e4ec9b4243

**Comment by malgeri** [comment]
Hi,

thanks! 
indeed bea8627 his is a better implementation keeping compatibility with paho.mqtt 1.x.

Thanks and best,
                                l.
