### ISSUE TITLE
Shelly blinds keep changing state in Domoticz

### ISSUE THREAD

**Issue by Xavier82** [enesbcs/shellyteacher4domo#48]
Hi Alexander, 

Don't know where to start but since I think the issue is being caused by MQTT I start my search here.

Since today I stand out that in Domoticz the Shelly Blinds keep changing their state from open to close en from close to open without actually really going up or down. This only happens at the blinds other devices don't show this behaviour.
Any idea what this could be?
I reran Shellyteacher4Domo (updated) Windows version and rebooted all devices but no changes were detected in Domoticz.
Nothing has changed.  

I wanted to rerun ShellyTeacher4Domo with my Rpi but after upgrade I get this error:
`
pi@raspberrypi:~/shellyteacher4domo $ sudo ./run.sh
Mosquitto conf found.
persistence ENABLED
TKInter init failed no display name and no $DISPLAY environment variable
Ini file exists
/home/pi/shellyteacher4domo/shellyteacher4domo.py:481: DeprecationWarning: Callback API version 1 is deprecated, update                                      to latest version
  mqttclient1 = MQTTClient(mqttcompatibility) #gen1
Connecting to MQTT server...
/home/pi/shellyteacher4domo/shellyteacher4domo.py:497: DeprecationWarning: Callback API version 1 is deprecated, update                                      to latest version
  mqttclient2 = MQTTClient(mqttcompatibility) #gen2
Connecting to MQTT server...
/home/pi/shellyteacher4domo/shellyteacher4domo.py:512: DeprecationWarning: Callback API version 1 is deprecated, update                                      to latest version
  mqttclient3 = MQTTClientOnlineCheck(mqttcompatibility) #gen2 online
Connecting to MQTT server...
/home/pi/shellyteacher4domo/shellyteacher4domo.py:524: DeprecationWarning: Callback API version 1 is deprecated, update                                      to latest version
  mqttclient4 = MQTTClientOnlineCheck(mqttcompatibility) #gen2 online
Traceback (most recent call last):
  File "/home/pi/shellyteacher4domo/shellyteacher4domo.py", line 552, in <module>
    loopok2 = connect_mqtt()
  File "/home/pi/shellyteacher4domo/shellyteacher4domo.py", line 525, in connect_mqtt
    mqttclient4.subscribechannel = settings.data['trigger_topic4']
KeyError: 'trigger_topic4'
`

**Comment by enesbcs** [comment]
> I wanted to rerun ShellyTeacher4Domo with my Rpi but after upgrade I get this error: "/home/pi/shellyteacher4domo/shellyteacher4domo.py", line 525, in connect_mqtt mqttclient4.subscribechannel = settings.data['trigger_topic4'] KeyError: 'trigger_topic4'`

Please erase full directory and download shellyteacher again. This error message caues as the settings.py structure changed 2 month ago.

Or you can use the windows version, which does not use external settings.py.

**Comment by Xavier82** [comment]
Hi,

since the python version didn't worked I used the windows version.
But still the problem exists in Domoticz? The status keeps flipping from open to closed multiple times in a minute.
Any idea why this happens?

**Comment by enesbcs** [comment]
> Hi,
> 
> since the python version didn't worked I used the windows version. But still the problem exists in Domoticz? The status keeps flipping from open to closed multiple times in a minute. Any idea why this happens?

I does not have any kind of blinds, so i have no idea. MQTT realtime debugging may help you.
