### ISSUE TITLE
Domoticz docker persistent data

### ISSUE THREAD

**Issue by jcligny** [enesbcs/shellyteacher4domo#49]
Hello.

Sorry I didn't find another issue.

Mine is Domoticz working from a docker, when I make a docker compose down I loose all my MQTT autodiscovery generated from shellyteacher4domo.

I'm new with docker but I know how to mount volumes to make them persistents.

Could you please hepl me to make persistent data after I ran shellyteacher4domo and after I decide to make a docker compose down for Domoticz ?

Thank you in advance for your help.

Jérôme.

**Comment by enesbcs** [comment]
Please read related howtows:
https://www.homeautomationguy.io/blog/docker-tips/configuring-the-mosquitto-mqtt-docker-container-for-use-with-home-assistant

or ask you question in a docker related forum.
