### ISSUE TITLE
Plugsplugs

### ISSUE THREAD

**Issue by gvandick** [enesbcs/shellyteacher4domo#51]
I use more shellly plugsplugs

I I add a new one then it only works if I make two different MQTT autodiscovery with different prefix names.
Otherwise the behavior of the two plugs are the same. On/Of en also the data energy use.

I aspect that the ID of each plug makes the plug unique in combination with the prefix.

**Comment by enesbcs** [comment]
This is not an issue of the app, please make sure that every plusplugs has different MQTT prefix in its own device settings.
When you report a possible problem, please add details, like names, settings, etc, otherwise there are nothing i can do with it, except closing.

**Comment by gvandick** [comment]
Oke

Thx for your reply

Regards

Gerard
________________________________
Van: Alexander Nagy ***@***.***>
Verzonden: zondag 24 maart 2024 11:22
Aan: enesbcs/shellyteacher4domo ***@***.***>
CC: Gerard ***@***.***>; Author ***@***.***>
Onderwerp: Re: [enesbcs/shellyteacher4domo] Plugsplugs (Issue #51)


This is not an issue of the app, please make sure that every plusplugs has different MQTT prefix in its own device settings.
When you report a possible problem, please add details, like names, settings, etc, otherwise there are nothing i can do with it, except closing.
