### ISSUE TITLE
Shelly H&T gen3 seen as switch device instead of temperature and humidity device

### ISSUE THREAD

**Issue by shakisha** [enesbcs/shellyteacher4domo#55]
Please, check image and logs:

![CleanShot 2024-05-29 at 22 29 04](https://github.com/enesbcs/shellyteacher4domo/assets/7482626/a2eb0809-f4fb-4978-af0c-d95a76157187)

on_message::payload::{"id":1,"src":"shellyhtg3-543204538f44","dst":"shellies_discovery","result":{"ble":{"enable":false,"rpc":{"enable":true}},"cloud":{"enable":true,"server":"shelly-57-eu.shelly.cloud:6022/jrpc"},"devicepower:0":{},"ht_ui":{"temperature_unit":"C"},"humidity:0":{"id":0, "name":null, "report_thr":5.0, "offset":0.0},"mqtt":{"enable":true,"server":"10.0.1.110:1883","client_id":"shellyht-terraza","user":"mqtt","ssl_ca":null,"topic_prefix":"shellyht-terraza","rpc_ntf":true,"status_ntf":false,"use_client_cert":false,"enable_rpc":true,"enable_control":true},"sys":{"device":{"name":null,"mac":"543204538F44","fw_id":"20240522-112842/1.3.2-g34c651b","discoverable":true},"location":{"tz":"Europe/Madrid","lat":38.422300,"lon":-0.697100},"debug":{"level":2,"file_level":null,"mqtt":{"enable":false},"websocket":{"enable":false},"udp":{"addr":null}},"ui_data":{},"rpc_udp":{"dst_addr":null,"listen_port":null},"sntp":{"server":"time.google.com"},"cfg_rev":11},"temperature:0":{"id":0, "name":null, "report_thr_C": 0.5, "offset_C": 0.0},"wifi":{"ap":{"ssid":"ShellyHTG3-543204538F44","is_open":true, "enable":false},"sta":{"ssid":"Kawa636r","is_open":false, "enable":true, "ipv4mode":"dhcp","ip":null,"netmask":null,"gw":null,"nameserver":null},"sta1":{"ssid":null,"is_open":true, "enable":false, "ipv4mode":"dhcp","ip":null,"netmask":null,"gw":null,"nameserver":null},"roam":{"rssi_thr":-80,"interval":60}},"ws":{"enable":false,"server":null,"ssl_ca":"ca.pem"}}}
>>>GEN2 device shellyhtg3-543204538f44 shellyht-terraza found

**Comment by enesbcs** [comment]
Please check your MQTT broker with MQTT Explorer at path "homeassistant/shellyhtg3-543204538f44/sensor" there has to be the temperature config objects for Domoticz. This is what the Teacher does and if its in place, there is no issue.

If you enabled "Generic status update over MQTT" setting on the device side, temperature data will be sent after some time - it may be took hours on HT devices. Until the first data does not arrive, you wont see anything but switches, it is normal operation.

**Comment by shakisha** [comment]
@enesbcs  sorry, I didn't check Generic status update over MQTT. 
Now works perfect with shelly H&T, thank you so much, I'll close the issue.
