### ISSUE TITLE
Shelly EM3 support

### ISSUE THREAD

**Issue by orlando1967** [enesbcs/shellyteacher4domo#8]
Hi, thanks for your work.
Based on the code for the Shelly EM I have written the following to support the Shelly EM-3 which is very similar.

[SHEM-3]  # Shelly EM3
topic=%discovery_prefix%/switch/%shelly_id%-0/relay/config
payload={"name": "%shelly_id% Relay 0", "cmd_t": "~relay/0/command", "stat_t": "~relay/0", "pl_off": "off", "pl_on": "on", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false", "uniq_id": "%shelly_id%-relay-0", "qos": 0, "~": "shellies/%shelly_id%/"}
topic=%discovery_prefix%/sensor/%shelly_id%-0/energy/config
payload={"name": "%shelly_id% Energy 0", "stat_t": "~emeter/0/energy", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false", "frc_upd": "false", "enabled_by_default": false, "uniq_id": "%shelly_id%-energy-0", "qos": 0, "~": "shellies/%shelly_id%/", "dev_cla": "energy", "stat_cla": "total_increasing", "unit_of_meas": "Wh", "val_tpl": "{{(value|float/60)|round(2)}}"}
topic=%discovery_prefix%/sensor/%shelly_id%-0/returnedenergy/config
payload={"name": "%shelly_id% Returned Energy 0", "stat_t": "~emeter/0/returned_energy", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false", "frc_upd": "false", "enabled_by_default": false, "uniq_id": "%shelly_id%-returnedenergy-0", "qos": 0, "~": "shellies/%shelly_id%/", "dev_cla": "energy", "stat_cla": "total_increasing", "unit_of_meas": "Wh", "val_tpl": "{{(value|float/60)|round(2)}}"}
topic=%discovery_prefix%/sensor/%shelly_id%-0/power/config
payload={"name": "%shelly_id% Power 0", "stat_t": "~emeter/0/power", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false", "frc_upd": "false", "enabled_by_default": true, "uniq_id": "%shelly_id%-power-0", "qos": 0, "~": "shellies/%shelly_id%/", "dev_cla": "power", "stat_cla": "measurement", "unit_of_meas": "W", "val_tpl": "{{value|float|round(1)}}"}
topic=%discovery_prefix%/sensor/%shelly_id%-0/reactivepower/config
payload={"name": "%shelly_id% Reactive Power 0", "stat_t": "~emeter/0/reactive_power", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false", "frc_upd": "false", "enabled_by_default": true, "uniq_id": "%shelly_id%-reactivepower-0", "qos": 0, "~": "shellies/%shelly_id%/", "dev_cla": "power", "stat_cla": "measurement", "unit_of_meas": "W", "val_tpl": "{{value|float|round(1)}}"}
topic=%discovery_prefix%/sensor/%shelly_id%-0/voltage/config
payload={"name": "%shelly_id% Voltage 0", "stat_t": "~emeter/0/voltage", "frc_upd": "false", "enabled_by_default": true, "uniq_id": "%shelly_id%-voltage-0", "qos": 0, "~": "shellies/%shelly_id%/", "dev_cla": "voltage", "stat_cla": "measurement", "unit_of_meas": "V", "val_tpl": "{{value|float|round(1)}}", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false"}
topic=%discovery_prefix%/sensor/%shelly_id%-0/total/config
payload={"name": "%shelly_id% Total 0", "stat_t": "~emeter/0/total", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false", "frc_upd": "false", "enabled_by_default": true, "uniq_id": "%shelly_id%-total-0", "qos": 0, "~": "shellies/%shelly_id%/", "dev_cla": "energy", "stat_cla": "total_increasing", "unit_of_meas": "Wh", "val_tpl": "{{value|round(2)}}"}
topic=%discovery_prefix%/sensor/%shelly_id%-0/totalreturned/config
payload={"name": "%shelly_id% Total Returned 0", "stat_t": "~emeter/0/total_returned", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false", "frc_upd": "false", "enabled_by_default": true, "uniq_id": "%shelly_id%-totalreturned-0", "qos": 0, "~": "shellies/%shelly_id%/", "dev_cla": "energy", "stat_cla": "total_increasing", "unit_of_meas": "Wh", "val_tpl": "{{value|round(2)}}"}
topic=%discovery_prefix%/sensor/%shelly_id%-1/energy/config
payload={"name": "%shelly_id% Energy 1", "stat_t": "~emeter/1/energy", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false", "frc_upd": "false", "enabled_by_default": false, "uniq_id": "%shelly_id%-energy-1", "qos": 0, "~": "shellies/%shelly_id%/", "dev_cla": "energy", "stat_cla": "total_increasing", "unit_of_meas": "Wh", "val_tpl": "{{(value|float/60)|round(2)}}"}
topic=%discovery_prefix%/sensor/%shelly_id%-1/returnedenergy/config
payload={"name": "%shelly_id% Returned Energy 1", "stat_t": "~emeter/1/returned_energy", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false", "frc_upd": "false", "enabled_by_default": false, "uniq_id": "%shelly_id%-returnedenergy-1", "qos": 0, "~": "shellies/%shelly_id%/", "dev_cla": "energy", "stat_cla": "total_increasing", "unit_of_meas": "Wh", "val_tpl": "{{(value|float/60)|round(2)}}"}
topic=%discovery_prefix%/sensor/%shelly_id%-1/power/config
payload={"name": "%shelly_id% Power 1", "stat_t": "~emeter/1/power", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false", "frc_upd": "false", "enabled_by_default": true, "uniq_id": "%shelly_id%-power-1", "qos": 0, "~": "shellies/%shelly_id%/", "dev_cla": "power", "stat_cla": "measurement", "unit_of_meas": "W", "val_tpl": "{{value|float|round(1)}}"}
topic=%discovery_prefix%/sensor/%shelly_id%-1/reactivepower/config
payload={"name": "%shelly_id% Reactive Power 1", "stat_t": "~emeter/1/reactive_power", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false", "frc_upd": "false", "enabled_by_default": true, "uniq_id": "%shelly_id%-reactivepower-1", "qos": 0, "~": "shellies/%shelly_id%/", "dev_cla": "power", "stat_cla": "measurement", "unit_of_meas": "W", "val_tpl": "{{value|float|round(1)}}"}
topic=%discovery_prefix%/sensor/%shelly_id%-1/voltage/config
payload={"name": "%shelly_id% Voltage 1", "stat_t": "~emeter/1/voltage", "frc_upd": "false", "enabled_by_default": true, "uniq_id": "%shelly_id%-voltage-1", "qos": 0, "~": "shellies/%shelly_id%/", "dev_cla": "voltage", "stat_cla": "measurement", "unit_of_meas": "V", "val_tpl": "{{value|float|round(1)}}", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false"}
topic=%discovery_prefix%/sensor/%shelly_id%-1/total/config
payload={"name": "%shelly_id% Total 1", "stat_t": "~emeter/1/total", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false", "frc_upd": "false", "enabled_by_default": true, "uniq_id": "%shelly_id%-total-1", "qos": 0, "~": "shellies/%shelly_id%/", "dev_cla": "energy", "stat_cla": "total_increasing", "unit_of_meas": "Wh", "val_tpl": "{{value|round(2)}}"}
topic=%discovery_prefix%/sensor/%shelly_id%-1/totalreturned/config
payload={"name": "%shelly_id% Total Returned 1", "stat_t": "~emeter/1/total_returned", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false", "frc_upd": "false", "enabled_by_default": true, "uniq_id": "%shelly_id%-totalreturned-1", "qos": 0, "~": "shellies/%shelly_id%/", "dev_cla": "energy", "stat_cla": "total_increasing", "unit_of_meas": "Wh", "val_tpl": "{{value|round(2)}}"}
topic=%discovery_prefix%/sensor/%shelly_id%-2/energy/config
payload={"name": "%shelly_id% Energy 2", "stat_t": "~emeter/2/energy", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false", "frc_upd": "false", "enabled_by_default": false, "uniq_id": "%shelly_id%-energy-2", "qos": 0, "~": "shellies/%shelly_id%/", "dev_cla": "energy", "stat_cla": "total_increasing", "unit_of_meas": "Wh", "val_tpl": "{{(value|float/60)|round(2)}}"}
topic=%discovery_prefix%/sensor/%shelly_id%-2/returnedenergy/config
payload={"name": "%shelly_id% Returned Energy 2", "stat_t": "~emeter/2/returned_energy", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false", "frc_upd": "false", "enabled_by_default": false, "uniq_id": "%shelly_id%-returnedenergy-2", "qos": 0, "~": "shellies/%shelly_id%/", "dev_cla": "energy", "stat_cla": "total_increasing", "unit_of_meas": "Wh", "val_tpl": "{{(value|float/60)|round(2)}}"}
topic=%discovery_prefix%/sensor/%shelly_id%-2/power/config
payload={"name": "%shelly_id% Power 2", "stat_t": "~emeter/2/power", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false", "frc_upd": "false", "enabled_by_default": true, "uniq_id": "%shelly_id%-power-2", "qos": 0, "~": "shellies/%shelly_id%/", "dev_cla": "power", "stat_cla": "measurement", "unit_of_meas": "W", "val_tpl": "{{value|float|round(1)}}"}
topic=%discovery_prefix%/sensor/%shelly_id%-2/reactivepower/config
payload={"name": "%shelly_id% Reactive Power 2", "stat_t": "~emeter/2/reactive_power", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false", "frc_upd": "false", "enabled_by_default": true, "uniq_id": "%shelly_id%-reactivepower-2", "qos": 0, "~": "shellies/%shelly_id%/", "dev_cla": "power", "stat_cla": "measurement", "unit_of_meas": "W", "val_tpl": "{{value|float|round(1)}}"}
topic=%discovery_prefix%/sensor/%shelly_id%-2/voltage/config
payload={"name": "%shelly_id% Voltage 2", "stat_t": "~emeter/2/voltage", "frc_upd": "false", "enabled_by_default": true, "uniq_id": "%shelly_id%-voltage-2", "qos": 0, "~": "shellies/%shelly_id%/", "dev_cla": "voltage", "stat_cla": "measurement", "unit_of_meas": "V", "val_tpl": "{{value|float|round(1)}}", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false"}
topic=%discovery_prefix%/sensor/%shelly_id%-2/total/config
payload={"name": "%shelly_id% Total 2", "stat_t": "~emeter/2/total", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false", "frc_upd": "false", "enabled_by_default": true, "uniq_id": "%shelly_id%-total-2", "qos": 0, "~": "shellies/%shelly_id%/", "dev_cla": "energy", "stat_cla": "total_increasing", "unit_of_meas": "Wh", "val_tpl": "{{value|round(2)}}"}
topic=%discovery_prefix%/sensor/%shelly_id%-2/totalreturned/config
payload={"name": "%shelly_id% Total Returned 2", "stat_t": "~emeter/2/total_returned", "avty_t": "~online", "pl_avail": "true", "pl_not_avail": "false", "frc_upd": "false", "enabled_by_default": true, "uniq_id": "%shelly_id%-totalreturned-2", "qos": 0, "~": "shellies/%shelly_id%/", "dev_cla": "energy", "stat_cla": "total_increasing", "unit_of_meas": "Wh", "val_tpl": "{{value|round(2)}}"}

**Comment by enesbcs** [comment]
Yep the 3EM MQTT looks very similar, did you try these templates?

**Comment by enesbcs** [comment]
support added at commit https://github.com/enesbcs/shellyteacher4domo/commit/70fdd0a254130ba8aec63e9fa68d908b4d51c0b6

**Comment by orlando1967** [comment]
Yes, of course I tried. It seems to work fine.

**Comment by enesbcs** [comment]
Thank you for testing and adding, closing issue now!
